--- 
title: "Dataset guide"
author: "Joyce Robbins"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE,
                      cache = TRUE)
library(tidyverse)
```


# R Packages

## Exploring data in packages locally:

Install **datacat**:

```{r, eval = FALSE}
remotes::install("jtr13/datacat")
```

View information with:

```{r, eval = FALSE}
library(datacat)
get_dataset_info("ggplot2") %>% View()
```

## List of packages with data


```{r}
show <- function(packagename) {
  cat(packageDescription(packagename)$Description)
  datacat::get_dataset_info(packagename, 
                   include_package = FALSE,
                   link = TRUE) %>% 
    DT::datatable(escape = FALSE)
}
```

### AER

```{r, results='asis'}
show("AER")
```

### alr4

```{r, results='asis'}
show("alr4")
```

### boot

```{r, results='asis'}
show("boot")
```

### dslabs

```{r, results='asis'}
show("dslabs")
```


### MASS

```{r, results='asis'}
show("MASS")
```

### vcd

```{r, results='asis'}
show("vcd")
```
